### ISSUE TITLE
Keyerror 'data'

### ISSUE THREAD

**Issue by jaikishantulswani** [mdsecactivebreach/LinkedInt#11]
Getting this at the end

Traceback (most recent call last):
  File "LinkedInt.py", line 447, in <module>
    prefix = content['data']['pattern']
KeyError: 'data'

**Comment by robisonr** [comment]
Getting the same thing at a different line:

Traceback (most recent call last):
  File "LinkedInt.py", line 388, in <module>
    prefix = content['data']['pattern']
KeyError: 'data'
