### ISSUE TITLE
UnboundLocalError: local variable 'user' referenced before assignment

### ISSUE THREAD

**Issue by nccdhelton** [mdsecactivebreach/LinkedInt#14]
Running LinkedInt on either macOS or Kali Linux, I encounter this error whenever I try to do a scrape.

Here is a transcript of the session (with company and person info redacted)

```
[*] Enter search Keywords (use quotes for more percise results)


[*] Enter filename for output (exclude file extension)
LinkedInt-Test

[*] Filter by Company? (Y/N): 
Y

[*] Specify a Company ID (Provide ID or leave blank to automate): 
<REDACTED>

[*] Enter e-mail domain suffix (eg. contoso.com): 
<REDACTED>.com

[*] Select a prefix for e-mail generation (auto,full,firstlast,firstmlast,flast,first.last,fmlast,lastfirst): 
auto 

[*] Automaticly using Hunter IO to determine best Prefix
[!] {first}
[+] Found first prefix

[!] Cannot load main LinkedIn page
<REDACTED>
[*] Obtained new session: <REDACTED>

[*] Using company ID: <REDACTED>
https://www.linkedin.com/voyager/api/search/cluster?count=40&guides=List(v->PEOPLE,facetCurrentCompany-><REDACTED>)&origin=OTHER&q=guided&start=0
[*] 122 Results Found
[*] Fetching 3 Pages

[*] Fetching page 0 with 40 results
[*] No picture found for <REDACTED>, ___
Traceback (most recent call last):
  File "LinkedInt.py", line 477, in <module>
    get_search()
  File "LinkedInt.py", line 273, in get_search
    email = '{}@{}'.format(user, suffix)
UnboundLocalError: local variable 'user' referenced before assignment
```

**Comment by airhack87** [comment]
Same issue I encountered, did u find wat the issue was ?

**Comment by Kaan191** [comment]
Because of a subtle LinkedIn UI change of the banner / top card of Company profiles. 

Try swapping the CSS Selector for the all_employees_links variable, from ‘.org-company-employees-snackbar__details-highlight’ to ‘.mt2’, in Company.py, line 45. Worked for me. 



On 14 Jan 2019, at 17:31, airhack87 <notifications@github.com> wrote:

Same issue I encountered, did u find wat the issue was ?

**Comment by nccdhelton** [comment]
Figured out what the problem is...there is no logic to handle a 'first' email format (first-name-only is used for the email address, eg. bob@contoso.com).  I added the following if statement on line 272...

```
if prefix == 'first':
    user = '{}'.format(fname)
```

Now it works fine for my use case.
